[package]
name = "flocon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "color"] }
ctrlc = { version = "3.4", features = ["termination"] }
fuse-backend-rs = { git = "https://github.com/Xowap/fuse-backend-rs.git", branch = "feature/mount-flags", features = ["fusedev", "virtiofs"] }
nix = "0.24"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libc = "0.2.174"

r2d2               = "0.8"
r2d2_sqlite        = "0.31.0"
rusqlite           = { version = "0.37", features = ["blob"] }
rusqlite_migration = "2.3.0"